service: lumix-ai-service

provider:
  name: aws
  runtime: python3.11
  region: ${env:AWS_REGION, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 1024
  timeout: 300

  # API Gateway HTTP API Configuration
  httpApi:
    cors:
      allowedOrigins:
        - '*'  # Change to your Vercel domain in production: 'https://your-app.vercel.app'
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: false

  environment:
    AWS_BEDROCK_MODEL_ID: ${env:AWS_BEDROCK_MODEL_ID}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - bedrock:InvokeModel
      Resource: "*"
    - Effect: Allow
      Action:
        - textract:DetectDocumentText
        - textract:AnalyzeDocument
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: "arn:aws:s3:::${env:S3_BUCKET_NAME}/*"

functions:
  # Main API Gateway - handles ALL FastAPI endpoints via Mangum
  api:
    handler: src.main.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'
      - httpApi:
          path: /
          method: '*'
    description: Lumix AI Service - All AI endpoints via FastAPI
    timeout: 600  # Longer timeout for agent operations

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: true
